DROP TABLE IF EXISTS map CASCADE;
exports = (db) => { CREATE TABLE map (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  pin_id INTEGER REFERENCES pin(id) ON DELETE CASCADE,
  latitude INTEGER NOT NULL,
  longitude INTEGER NOT NULL);
}
