DROP TABLE IF EXISTS favorite_maps CASCADE;
CREATE TABLE favorite_maps (
  id SERIAL PRIMARY KEY NOT NULL,
  map_user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES map(id) ON DELETE CASCADE);
